name: ML CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Debug (VERY IMPORTANT)
    - name: Debug files
      run: |
        echo "Current directory:"
        pwd
        echo "Files in repo:"
        ls -R

    # Step 3: Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Step 5: Run tests
    - name: Run Tests
      run: |
        pytest

    # Step 6: Train model
    - name: Train Model
      run: |
        python train.py
        